### ISSUE TITLE
 Class 'CssEditor\Controller\Admin\IndexController' not found

### ISSUE THREAD

**Issue by pprw** [omeka-s-modules/CSSEditor#1]
I have an error  `Class 'CssEditor\Controller\Admin\IndexController' not found` with this module.

P-S: Readme link doc send to Mapping doc.

**Comment by kimisgold** [comment]
The readme link should be fixed now, thanks! On what view do you get the controller error?

**Comment by pprw** [comment]
I have the controller error when visiting /admin/site/s/mysite/css-editor/index (the link to csseditor inside a site settings).
