### ISSUE TITLE
Test for controller error in different environments

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/CSSEditor#2]
The main CSS Editor interface threw a controller error when running on non-Mac OS environments because of a namespace casing issue (#1). Test that the CSS Editor interface is accessible when running on Mac OS and an actual server.

**Comment by jerielizabeth** [comment]
Tested in a local, MacOS environment. Module successfully loaded and registered CSS changes.

<img width="1430" alt="Screenshot 2019-09-17 21 07 34" src="https://user-images.githubusercontent.com/1447744/65111014-34bf1700-d98f-11e9-8d24-05d9edb04d27.png">

<img width="897" alt="Screenshot 2019-09-17 21 05 16" src="https://user-images.githubusercontent.com/1447744/65110968-0ccfb380-d98f-11e9-8980-f09de2c427ab.png">

Will test next in non-Mac environment.

**Comment by jerielizabeth** [comment]
Tested on an Ubuntu server, hosted by Digital Ocean.

Again, the module successfully loaded and registered the CSS changes.

<img width="1431" alt="Screenshot 2019-09-17 21 35 57" src="https://user-images.githubusercontent.com/1447744/65112236-d3e60d80-d993-11e9-84aa-17fc98138d97.png">

<img width="1430" alt="Screenshot 2019-09-17 21 39 47" src="https://user-images.githubusercontent.com/1447744/65112240-d6486780-d993-11e9-9998-c7fb27cbe78b.png">

<img width="1434" alt="Screenshot 2019-09-17 21 40 01" src="https://user-images.githubusercontent.com/1447744/65112249-db0d1b80-d993-11e9-91f6-09af3180ed8a.png">

**Comment by kimisgold** [comment]
@jerielizabeth Perfect, thank you!
